name: Bot scan
on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
permissions:
  issues: write
  pull-requests: write

jobs:
  Snyk_scanning:
    name: Snyk Bot scan
    runs-on: ubuntu-latest
    # Expose step outputs as job outputs
    outputs:
      snyk_out: ${{ steps.set-snyk-output.outputs.snyk_json }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Snyk Bot scan
        continue-on-error: true
        run: |
         rm -rf node_modules
         rm -f package-lock.json
         echo "----------NPM install------------"
         npm install
         echo "----------Download Latest Snyk CLI-----------"
            curl -Lo ./snyk "https://github.com/snyk/snyk/releases/download/v1.1293.0/snyk-linux"
            chmod +x snyk
            ls -lrt
            echo "----------Authenticating Snyk-----------"
            ./snyk auth ${{ secrets.SNYK_TOKEN }}
            echo "----------Snyk Scanning-----------"
            ./snyk test --all-projects -d --json > snyk_output.json
      - name: Set filtered Snyk JSON as output
        id: set-snyk-output
        run: |
          # Escape the JSON and set it as output
          snyk_json=$(cat snyk_output.json | jq -Rr @json)
          echo "snyk_json=$snyk_json" >> $GITHUB_OUTPUT
          
  # TruffleHog_scanning:
  #   name: TruffleHog Bot scan
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0 # fetch all history so multiple commits can be scanned
  #     - name: TruffleHog Bot scan
  #       continue-on-error: true
  #       uses: trufflesecurity/TruffleHog-Enterprise-Github-Action@main
  #       with:
  #           args: ${{ github.event.repository.default_branch }} $GITHUB_HEAD_REF --json
  TruffleHog_scanning:
    name: TruffleHog Bot scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # fetch all history so multiple commits can be scanned
      - name: TruffleHog Bot scan
        continue-on-error: false
        run: |
          curl -q "https://storage.googleapis.com/thog-releases/trufflehog-scanner/latest/fetch.sh" | bash
          ./trufflehog git ${{ github.event.repository.default_branch }} $GITHUB_HEAD_REF 
          
  BotCheck:
    permissions: write-all
    runs-on: ubuntu-latest
    needs: [Snyk_scanning, TruffleHog_scanning]
    steps:
      - uses: Vigneshkna/pr-scan-action@dev-pr-init
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SNYK_OUT: ${{ needs.Snyk_scanning.outputs.snyk_out}}
